"""Generate data/official_resources.json and data/regional_wards.json."""
import json
import os

def t(zh, en, ja):
    return {"zh-TW": zh, "en": en, "ja": ja}

RESOURCES = [
    {
        "id": "res_isa_immigration",
        "tier": "official",
        "title": t("出入國在留管理廳｜入國・在留手續", "ISA | Immigration procedures", "出入国在留管理庁｜入国・在留手続"),
        "url": "https://www.moj.go.jp/isa/index.html",
        "task_ids": ["task_arrival"],
        "priority": 10,
        "summary": t("日本入國與在留相關官方說明", "Official immigration information", "入国・在留に関する公式情報"),
    },
    {
        "id": "res_isa_residence_card",
        "tier": "official",
        "title": t("出入國在留管理廳｜在留卡", "ISA | Residence card", "出入国在留管理庁｜在留カード"),
        "url": "https://www.moj.go.jp/isa/publications/materials/newimmiact_3_zhotizen.html",
        "task_ids": ["task_residence_card", "task_residence_expiry"],
        "priority": 10,
        "summary": t("在留卡的官方說明（含中文）", "Official residence card guide", "在留カードの公式案内"),
    },
    {
        "id": "res_boj_exchange",
        "tier": "official",
        "title": t("日本銀行｜外幣兌換須知", "Bank of Japan | Currency exchange", "日本銀行｜外貨両替の案内"),
        "url": "https://www.boj.or.jp/en/about/education/oshiete/exchange/index.htm",
        "task_ids": ["task_exchange"],
        "priority": 8,
        "summary": t("兌換日圓時可參考的官方資訊", "Official info on exchanging yen", "円への両替に関する情報"),
    },
    {
        "id": "res_suica_guide",
        "tier": "semi_official",
        "title": t("JR東日本｜Suica 交通卡", "JR East | Suica IC card", "JR東日本｜Suica交通系ICカード"),
        "url": "https://www.jreast.co.jp/multi/en/welcomesuica/welcomesuica.html",
        "task_ids": ["task_transport_card"],
        "priority": 9,
        "summary": t("Suica 購買與使用方法", "How to buy and use Suica", "Suicaの購入と使い方"),
    },
    {
        "id": "res_jasso_study",
        "tier": "semi_official",
        "title": t("JASSO｜留學生生活支援", "JASSO | Support for international students", "JASSO｜留学生生活支援"),
        "url": "https://www.studyinjapan.go.jp/en/",
        "task_ids": ["task_contact_school", "task_school_enroll", "task_orientation"],
        "priority": 9,
        "summary": t("日本留學官方生活資訊入口", "Official study-in-Japan portal", "留学日本の公式ポータル"),
    },
    {
        "id": "res_soumu_resident",
        "tier": "official",
        "title": t("總務省｜住民登錄說明", "MIC | Resident registration", "総務省｜住民登録の説明"),
        "url": "https://www.soumu.go.jp/menu_seiho/seiho/seido/jumin/ju_min.html",
        "task_ids": ["task_address", "task_housing_confirm"],
        "priority": 10,
        "summary": t("住民登錄的國家層級官方說明", "National guide to resident registration", "住民登録の国の公式説明"),
    },
    {
        "id": "res_ward_office_regional",
        "tier": "official",
        "title": t("區役所｜住民登錄（依居住地）", "Ward office | Resident registration", "区役所｜住民登録（居住地による）"),
        "url": "",
        "resolver": "ward_office",
        "task_ids": ["task_address", "task_insurance", "task_mynumber", "task_pension"],
        "priority": 11,
        "summary": t("您居住地的區役所官方網站", "Official ward office for your area", "お住まいの区役所公式サイト"),
    },
    {
        "id": "res_mhlw_nhi",
        "tier": "official",
        "title": t("厚生勞動省｜國民健康保險", "MHLW | National Health Insurance", "厚生労働省｜国民健康保険"),
        "url": "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iryouhoken/iryouhoken15/index.html",
        "task_ids": ["task_insurance", "task_healthcare_guide"],
        "priority": 10,
        "summary": t("國民健康保險官方說明", "Official NHI information", "国民健康保険の公式案内"),
    },
    {
        "id": "res_mynumber",
        "tier": "official",
        "title": t("內閣府｜My Number（個人編號）", "Cabinet Office | My Number", "内閣府｜マイナンバー"),
        "url": "https://www.kojinbango-card.go.jp/en/",
        "task_ids": ["task_mynumber"],
        "priority": 9,
        "summary": t("個人編號通知卡官方說明", "Official My Number guide", "マイナンバーの公式案内"),
    },
    {
        "id": "res_nenkin_student",
        "tier": "official",
        "title": t("日本年金機構｜學生納付特例", "Japan Pension Service | Student exemption", "日本年金機構｜学生納付特例"),
        "url": "https://www.nenkin.go.jp/service/kokunai/gakusei/gakusei.html",
        "task_ids": ["task_pension"],
        "priority": 10,
        "summary": t("學生國民年金免除申請官方說明", "Student pension exemption guide", "学生の年金免除の公式案内"),
    },
    {
        "id": "res_soumu_mobile",
        "tier": "official",
        "title": t("總務省｜手機契約（訪日外國人）", "MIC | Mobile contracts for visitors", "総務省｜携帯契約（訪日外国人）"),
        "url": "https://www.soumu.go.jp/menu_seiho/seiho/seido/joho_tsusin/mobilenet/kaigai.html",
        "task_ids": ["task_phone"],
        "priority": 9,
        "summary": t("外國人在日本辦理手機的官方說明", "Official mobile contract guide", "携帯契約の公式案内"),
    },
    {
        "id": "res_jp_bank",
        "tier": "official",
        "title": t("ゆうちょ銀行｜開戶（外國人）", "Japan Post Bank | Account opening", "ゆうちょ銀行｜口座開設（外国人）"),
        "url": "https://www.jp-bank.japanpost.jp/bank/en/ijpbnksttopmn/index.html",
        "task_ids": ["task_bank"],
        "priority": 10,
        "summary": t("郵政銀行開戶官方英文指南", "Official account opening guide", "口座開設の公式ガイド"),
    },
    {
        "id": "res_isa_work_permit",
        "tier": "official",
        "title": t("出入國在留管理廳｜資格外活動許可", "ISA | Permission to work part-time", "出入国在留管理庁｜資格外活動許可"),
        "url": "https://www.moj.go.jp/isa/applications/procedures/16-4.html",
        "task_ids": ["task_work_permit"],
        "priority": 10,
        "summary": t("打工許可官方申請說明", "Official part-time work permit guide", "アルバイト許可の公式案内"),
    },
    {
        "id": "res_police_110",
        "tier": "official",
        "title": t("警察廳｜110 緊急報案", "National Police Agency | Emergency 110", "警察庁｜110番緊急通報"),
        "url": "https://www.npa.go.jp/english/110.html",
        "task_ids": ["task_emergency_guide"],
        "priority": 10,
        "summary": t("報警方式官方說明", "How to call police in emergency", "110番の公式案内"),
    },
    {
        "id": "res_fire_119",
        "tier": "official",
        "title": t("消防廳｜119 緊急通報", "Fire and Disaster Mgmt | Emergency 119", "消防庁｜119番緊急通報"),
        "url": "https://www.fdma.go.jp/en/",
        "task_ids": ["task_emergency_guide"],
        "priority": 10,
        "summary": t("火災・救護通報官方說明", "How to call ambulance/fire", "119番の公式案内"),
    },
    {
        "id": "res_multilingual_helpline",
        "tier": "official",
        "title": t("東京｜多語言諮詢熱線", "Tokyo | Multilingual helpline", "東京｜多言語相談ホットライン"),
        "url": "https://www.metro.tokyo.lg.jp/english/guide/hotline.html",
        "task_ids": ["task_emergency_guide"],
        "priority": 8,
        "summary": t("緊急時多語言支援（東京）", "Multilingual support in Tokyo", "多言語緊急支援（東京）"),
    },
    {
        "id": "res_safety_tips",
        "tier": "official",
        "title": t("內閣府｜Safety tips 防災App", "Cabinet Office | Safety tips app", "内閣府｜Safety tips防災アプリ"),
        "url": "https://www.j-alert.go.jp/en/",
        "task_ids": ["task_disaster_prep"],
        "priority": 10,
        "summary": t("官方防災推播 App", "Official disaster alert app", "公式防災アプリ"),
    },
    {
        "id": "res_consumer_scam",
        "tier": "official",
        "title": t("消費者廳｜特殊詐欺防範", "Consumer Affairs Agency | Fraud prevention", "消費者庁｜特殊詐欺対策"),
        "url": "https://www.caa.go.jp/policies/policy/local_cooperation/local_consumer_administration/hotline/special_fraud/",
        "task_ids": ["task_scam_awareness"],
        "priority": 10,
        "summary": t("針對詐騙的官方防範說明", "Official scam prevention guide", "詐欺防止の公式案内"),
    },
    {
        "id": "res_mhlw_clinic",
        "tier": "official",
        "title": t("厚生勞動省｜醫療機構就醫方式", "MHLW | How to use healthcare", "厚生労働省｜医療機関の利用"),
        "url": "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iryouhoken/iryouhoken15/index_00002.html",
        "task_ids": ["task_healthcare_guide"],
        "priority": 9,
        "summary": t("持保險卡看病的官方說明", "Using health insurance at clinics", "保険証の使い方"),
    },
    {
        "id": "res_isa_extension",
        "tier": "official",
        "title": t("出入國在留管理廳｜在留期間更新", "ISA | Extension of period of stay", "出入国在留管理庁｜在留期間更新"),
        "url": "https://www.moj.go.jp/isa/applications/procedures/zairyu_koshin.html",
        "task_ids": ["task_residence_expiry"],
        "priority": 10,
        "summary": t("在留期限更新官方手續", "Official visa extension procedures", "在留更新の公式手続"),
    },
    {
        "id": "res_clair_life",
        "tier": "semi_official",
        "title": t("CLAIR｜外國人生活指南", "CLAIR | Living in Japan guide", "CLAIR｜外国人生活ガイド"),
        "url": "https://www.clair.or.jp/e/exchange/stay/life/",
        "task_ids": ["task_essentials", "task_temp_stay", "task_find_housing"],
        "priority": 7,
        "summary": t("地方政府國際交流協會的生活資訊", "Local government international exchange info", "自治体国際交流協会の生活情報"),
    },
    {
        "id": "res_mlit_housing",
        "tier": "official",
        "title": t("國土交通省｜租房須知", "MLIT | Rental housing guide", "国交省｜賃貸住宅の案内"),
        "url": "https://www.mlit.go.jp/common/001300312.pdf",
        "task_ids": ["task_lease", "task_find_housing"],
        "priority": 8,
        "summary": t("在日本租房的官方參考資料", "Official rental housing reference", "賃貸住宅の公式参考資料"),
    },
]

# Tokyo ward office official URLs (extend over time)
WARDS = {
    "文京区": {"url": "https://www.city.bunkyo.tokyo.jp/", "name": t("文京区役所", "Bunkyo City Office", "文京区役所")},
    "新宿区": {"url": "https://www.city.shinjuku.lg.jp/", "name": t("新宿区役所", "Shinjuku City Office", "新宿区役所")},
    "渋谷区": {"url": "https://www.city.shibuya.tokyo.jp/", "name": t("澀谷区役所", "Shibuya City Office", "渋谷区役所")},
    "豊島区": {"url": "https://www.city.toshima.lg.jp/", "name": t("豐島区役所", "Toshima City Office", "豊島区役所")},
    "台東区": {"url": "https://www.city.taito.lg.jp/", "name": t("台東区役所", "Taito City Office", "台東区役所")},
    "墨田区": {"url": "https://www.city.sumida.lg.jp/", "name": t("墨田区役所", "Sumida City Office", "墨田区役所")},
    "江東区": {"url": "https://www.city.koto.lg.jp/", "name": t("江東区役所", "Koto City Office", "江東区役所")},
    "品川区": {"url": "https://www.city.shinagawa.tokyo.jp/", "name": t("品川區役所", "Shinagawa City Office", "品川区役所")},
    "目黒区": {"url": "https://www.city.meguro.tokyo.jp/", "name": t("目黑区役所", "Meguro City Office", "目黒区役所")},
    "大田区": {"url": "https://www.city.ota.tokyo.jp/", "name": t("大田区役所", "Ota City Office", "大田区役所")},
    "世田谷区": {"url": "https://www.city.setagaya.lg.jp/", "name": t("世田谷区役所", "Setagaya City Office", "世田谷区役所")},
    "中野区": {"url": "https://www.city.tokyo-nakano.lg.jp/", "name": t("中野区役所", "Nakano City Office", "中野区役所")},
    "杉並区": {"url": "https://www.city.suginami.tokyo.jp/", "name": t("杉並区役所", "Suginami City Office", "杉並区役所")},
    "練馬区": {"url": "https://www.city.nerima.tokyo.jp/", "name": t("練馬区役所", "Nerima City Office", "練馬区役所")},
    "板橋区": {"url": "https://www.city.itabashi.tokyo.jp/", "name": t("板橋区役所", "Itabashi City Office", "板橋区役所")},
    "北区": {"url": "https://www.city.kita.tokyo.jp/", "name": t("北區役所", "Kita City Office", "北区役所")},
    "荒川区": {"url": "https://www.city.arakawa.tokyo.jp/", "name": t("荒川区役所", "Arakawa City Office", "荒川区役所")},
    "足立区": {"url": "https://www.city.adachi.tokyo.jp/", "name": t("足立区役所", "Adachi City Office", "足立区役所")},
    "葛飾区": {"url": "https://www.city.katsushika.lg.jp/", "name": t("葛飾区役所", "Katsushika City Office", "葛飾区役所")},
    "江戸川区": {"url": "https://www.city.edogawa.tokyo.jp/", "name": t("江戶川區役所", "Edogawa City Office", "江戸川区役所")},
    "千代田区": {"url": "https://www.city.chiyoda.lg.jp/", "name": t("千代田区役所", "Chiyoda City Office", "千代田区役所")},
    "中央区": {"url": "https://www.city.chuo.lg.jp/", "name": t("中央区役所", "Chuo City Office", "中央区役所")},
    "港区": {"url": "https://www.city.minato.tokyo.jp/", "name": t("港區役所", "Minato City Office", "港区役所")},
}

base = os.path.dirname(__file__)
data_dir = os.path.join(base, "..", "data")
os.makedirs(data_dir, exist_ok=True)

with open(os.path.join(data_dir, "official_resources.json"), "w", encoding="utf-8") as f:
    json.dump({"version": "1.0", "resources": RESOURCES}, f, ensure_ascii=False, indent=2)

with open(os.path.join(data_dir, "regional_wards.json"), "w", encoding="utf-8") as f:
    json.dump({"version": "1.0", "wards": WARDS}, f, ensure_ascii=False, indent=2)

print(f"Wrote {len(RESOURCES)} resources and {len(WARDS)} ward mappings")
