"""Generate data/schools.json — Japanese language schools for autocomplete."""
import json
import os

def s(id_, zh, en, ja, location, prefecture="東京都", city="東京", type="language_school"):
    return {
        "id": id_,
        "name": {"zh-TW": zh, "en": en, "ja": ja},
        "location": location,
        "prefecture": prefecture,
        "city": city,
        "type": type,
    }

SCHOOLS = [
    s("isi_takadanobaba", "ISI語言學院 高田馬場校", "ISI Language School Takadanobaba", "ISI日本語学校 高田馬場校", "東京都新宿區高田馬場"),
    s("isi_shinjuku", "ISI語言學院 新宿校", "ISI Language School Shinjuku", "ISI日本語学校 新宿校", "東京都新宿區西新宿"),
    s("isi_ikebukuro", "ISI語言學院 池袋校", "ISI Language School Ikebukuro", "ISI日本語学校 池袋校", "東京都豐島區東池袋"),
    s("arc_shinjuku", "ARC東京日本語學校 新宿校", "ARC Academy Shinjuku", "ARC東京日本語学校 新宿校", "東京都新宿區西新宿"),
    s("arc_omotesando", "ARC東京日本語學校 表參道校", "ARC Academy Omotesando", "ARC東京日本語学校 表参道校", "東京都澀谷區神宮前"),
    s("kudan", "九段日本語學院", "Kudan Institute of Japanese Language", "九段日本語学院", "東京都千代田區九段北"),
    s("genki_shinjuku", "GENKI Japanese and Culture School", "GENKI JACS Tokyo", "GENKI Japanese and Culture School", "東京都新宿區西新宿"),
    s("shibuya_gaigo", "澀谷外語學院", "Shibuya Gaigo Gakuin", "渋谷外語学院", "東京都澀谷區澀谷"),
    s("tokyo_central", "東京中央日本語學院", "Tokyo Central Japanese Language School", "東京中央日本語学院", "東京都新宿區大久保"),
    s("human_academy", "Human Academy 日本語學校 東京校", "Human Academy Japanese Language School Tokyo", "ヒューマンアカデミー日本語学校 東京校", "東京都新宿區西新宿"),
    s("kai", "KAI日本語學校", "KAI Japanese Language School", "KAI日本語学校", "東京都新宿區西新宿"),
    s("shinjuku_japanese", "新宿日本語學校", "Shinjuku Japanese Language Institute", "新宿日本語学校", "東京都新宿區高田馬場"),
    s("yoshida", "吉田日本語學校", "Yoshida Institute of Japanese Language", "吉田日本語学校", "東京都新宿區西早稻田"),
    s("akamonkai", "赤門會日本語學校 本校", "Akamonkai Japanese Language School", "赤門会日本語学校 本校", "東京都台東區台東"),
    s("akamonkai_nippori", "赤門會日本語學校 日暮里校", "Akamonkai Nippori", "赤門会日本語学校 日暮里校", "東京都荒川區東日暮里"),
    s("tcj", "東京中央日本語學院 TCJ", "Tokyo Central Japanese Language School", "東京中央日本語学院", "東京都新宿區西新宿"),
    s("ecc_tokyo", "ECC外語學院 新宿校", "ECC Japanese Language Institute Shinjuku", "ECC外国語学院 新宿校", "東京都新宿區西新宿"),
    s("waseda_edu", "早稻田edu日本語學校", "Waseda Edu Language School", "早稲田edu日本語学校", "東京都新宿區西早稻田"),
    s("samu", "SAMU語言學校", "SAMU Language School", "SAMU語学学校", "東京都台東區上野"),
    s("unitas_tokyo", "UNITAS日本語學校 東京校", "UNITAS Japanese Language School Tokyo", "UNITAS日本語学校 東京校", "東京都豐島區西池袋"),
    s("olj", "大阪日本語學院", "Osaka Japanese Language Institute", "大阪日本語学院", "大阪府大阪市中央區", prefecture="大阪府", city="大阪"),
    s("j_fic_osaka", "J FIC 大阪日本語學校", "J FIC Osaka", "J FIC 大阪日本語学校", "大阪府大阪市北區", prefecture="大阪府", city="大阪"),
    s("kansai_coc", "關西COC日本語學院", "Kansai COC Japanese Language School", "関西COC日本語学院", "大阪府大阪市西區", prefecture="大阪府", city="大阪"),
    s("kyoto_minsai", "京都民際日本語學校", "Kyoto Minsai Japanese Language School", "京都民際日本語学校", "京都府京都市中京區", prefecture="京都府", city="京都"),
    s("genki_kyoto", "GENKI Japanese and Culture School 京都校", "GENKI JACS Kyoto", "GENKI Japanese and Culture School 京都校", "京都府京都市中京區", prefecture="京都府", city="京都"),
    s("fukuoka_yamano", "福岡YAMANO日本語學校", "Fukuoka Yamano Japanese Language School", "福岡YAMANO日本語学校", "福岡縣福岡市中央區", prefecture="福岡県", city="福岡"),
    s("nagoya_yoshida", "名古屋YOSHIDA日本語學校", "Nagoya Yoshida Japanese Language School", "名古屋YOSHIDA日本語学校", "愛知縣名古屋市中區", prefecture="愛知県", city="名古屋"),
    s("hokkaido_japanese", "北海道日本語學院", "Hokkaido Japanese Language Academy", "北海道日本語学院", "北海道札幌市中央區", prefecture="北海道", city="札幌"),
    s("tokyo_university", "東京大學", "The University of Tokyo", "東京大学", "東京都文京區本鄉", city="東京", type="university"),
    s("waseda_university", "早稻田大學", "Waseda University", "早稲田大学", "東京都新宿區西早稻田", city="東京", type="university"),
    s("keio_university", "慶應義塾大學", "Keio University", "慶應義塾大学", "東京都港區三田", city="東京", type="university"),
    # --- Tokyo / Kanto language schools ---
    s("inter_cult", "インターカルト日本語学校", "Inter-Culture Institute of Japanese Language", "インターカルト日本語学校", "東京都新宿區西新宿"),
    s("tokyo_world", "東京ワールド日本語学校", "Tokyo World Japanese Language School", "東京ワールド日本語学校", "東京都新宿區高田馬場"),
    s("tokyo_intl_culture", "東京国際文化学院", "Tokyo International Culture Academy", "東京国際文化学院", "東京都新宿區大久保"),
    s("tokyo_japanese_edu", "東京日本語教育中心", "Tokyo Japanese Language Education Center", "東京日本語教育センター", "東京都新宿區西新宿"),
    s("nihon_kogakuin", "日本工學院專門學校 日本語科", "Nihon Kogakuin College Japanese Course", "日本工学院専門学校 日本語学科", "東京都新宿區西新宿"),
    s("ohara_ikebukuro", "大原日本語學院 池袋校", "Ohara Japanese Language School Ikebukuro", "大原日本語学院 池袋校", "東京都豐島區東池袋"),
    s("ohara_shinjuku", "大原日本語學院 新宿校", "Ohara Japanese Language School Shinjuku", "大原日本語学院 新宿校", "東京都新宿區西新宿"),
    s("waseda_intl_academy", "早稲田國際語學アカデミー", "Waseda International Language Academy", "早稲田国際語学アカデミー", "東京都新宿區高田馬場"),
    s("jc_japanese", "JC日本語學校", "JC Japanese Language School", "JC日本語学校", "東京都新宿區西新宿"),
    s("iidabashi_japanese", "飯田橋日本語學校", "Iidabashi Japanese Language School", "飯田橋日本語学校", "東京都千代田區飯田橋"),
    s("nisshinkyo", "日進日本語學校", "Nisshinkyo Japanese Language School", "日進日本語学校", "東京都豐島區東池袋"),
    s("tokyo_solar", "東京太陽外語學院", "Tokyo Solar Japanese Language School", "東京ソラ外国語学院", "東京都豐島區池袋"),
    s("best_japanese", "BEST日本語學院", "BEST Japanese Language Academy", "BEST日本語学院", "東京都新宿區高田馬場"),
    s("real_japanese", "REAL日本語學院", "REAL Japanese Language Academy", "リアル日本語学院", "東京都新宿區大久保"),
    s("asia_intl", "亞細亞國際語學中心", "Asia International Language Center", "アジア国際語学センター", "東京都新宿區西新宿"),
    s("tokyo_central_academy", "東京中央日本語學院 新宿校", "Tokyo Central Japanese Academy Shinjuku", "東京中央日本語学院 新宿校", "東京都新宿區西新宿"),
    s("tokyo_intl_lang", "東京國際外語學院", "Tokyo International Foreign Language Academy", "東京国際外語学院", "東京都新宿區高田馬場"),
    s("bunka_institute", "文化學院", "Bunka Institute of Language", "文化学院", "東京都新宿區高田馬場"),
    s("tokyo_gakuin", "東京學院日本語學校", "Tokyo Gakuin Japanese Language School", "東京学院日本語学校", "東京都新宿區西新宿"),
    s("tokyo_intl_academy", "東京國際學院", "Tokyo International Academy", "東京国際学院", "東京都新宿區大久保"),
    s("meros_academy", "メロス言語學院", "Meros Language Academy", "メロス言語学院", "東京都豐島區東池袋"),
    s("tokyo_fuji_lang", "東京富士日本語學校", "Tokyo Fuji Japanese Language School", "東京富士日本語学校", "東京都品川區大井"),
    s("tokyo_ikuei", "東京育英日本語學院", "Tokyo Ikuei Japanese Language School", "東京育英日本語学院", "東京都台東區上野"),
    s("tokyo_intl_japanese", "東京國際日本語學院", "Tokyo International Japanese College", "東京国際日本語学院", "東京都新宿區西新宿"),
    s("tokyo_nihongo_center", "東京日本語センター", "Tokyo Nihongo Center", "東京日本語センター", "東京都新宿區高田馬場"),
    s("shinjuku_nihongo_academy", "新宿日本語教育學院", "Shinjuku Japanese Language Academy", "新宿日本語教育学院", "東京都新宿區高田馬場"),
    s("tokyo_lang_academy", "東京語言學院", "Tokyo Language Academy", "東京語言学院", "東京都新宿區西新宿"),
    s("nihon_gakuin", "日本學院", "Nihon Gakuin Japanese Language School", "日本学院", "東京都新宿區西新宿"),
    s("tokyo_nihongo_gakuin", "東京日本語學院", "Tokyo Nihongo Gakuin", "東京日本語学院", "東京都新宿區大久保"),
    s("tokyo_intl_study", "東京國際留學學院", "Tokyo International Study Academy", "東京国際留学学院", "東京都豐島區池袋"),
    s("tokyo_school_japanese", "東京スクールオブジャパニーズ", "Tokyo School of Japanese", "東京スクールオブジャパニーズ", "東京都新宿區西新宿"),
    s("nihon_ringo", "日本語林檎學校", "Nihongo Ringo School", "日本語りんご学校", "東京都台東區浅草"),
    s("tokyo_one_japanese", "東京ONE日本語學校", "Tokyo ONE Japanese Language School", "東京ONE日本語学校", "東京都豐島區西池袋"),
    # --- Tokyo universities ---
    s("meiji_university", "明治大學", "Meiji University", "明治大学", "東京都千代田區神田駿河台", city="東京", type="university"),
    s("rikkyo_university", "立教大學", "Rikkyo University", "立教大学", "東京都豐島區西池袋", city="東京", type="university"),
    s("chuo_university", "中央大學", "Chuo University", "中央大学", "東京都文京區春日", city="東京", type="university"),
    s("hosei_university", "法政大學", "Hosei University", "法政大学", "東京都千代田區神田駿河台", city="東京", type="university"),
    s("sophia_university", "上智大學", "Sophia University", "上智大学", "東京都千代田區四番町", city="東京", type="university"),
    s("nihon_university", "日本大學", "Nihon University", "日本大学", "東京都千代田區九段南", city="東京", type="university"),
    s("toyo_university", "東洋大學", "Toyo University", "東洋大学", "東京都文京區白山", city="東京", type="university"),
    s("komazawa_university", "駒澤大學", "Komazawa University", "駒澤大学", "東京都世田谷區駒澤", city="東京", type="university"),
    s("senshu_university", "專修大學", "Senshu University", "専修大学", "東京都千代田區神田駿河台", city="東京", type="university"),
    s("gakushuin_university", "學習院大學", "Gakushuin University", "学習院大学", "東京都豐島區目白", city="東京", type="university"),
    s("tokyo_metropolitan", "東京都立大學", "Tokyo Metropolitan University", "東京都立大学", "東京都八王子市", city="東京", type="university"),
    s("tokyo_inst_tech", "東京工業大學", "Tokyo Institute of Technology", "東京工業大学", "東京都目黑區大岡山", city="東京", type="university"),
    s("hitotsubashi", "一橋大學", "Hitotsubashi University", "一橋大学", "東京都小平市", city="東京", type="university"),
    # --- Yokohama / Chiba ---
    s("yokohama_design", "橫濱設計學院 日本語科", "Yokohama Design College Japanese", "横浜デザイン学院 日本語科", "神奈川縣橫濱市西區", prefecture="神奈川県", city="横浜"),
    s("yokohama_intl_edu", "橫濱國際教育學院", "Yokohama International Education Academy", "横浜国際教育学院", "神奈川縣橫濱市西區", prefecture="神奈川県", city="横浜"),
    s("yokohama_system", "橫濱YMCA學院", "Yokohama YMCA College", "横浜YMCA学院", "神奈川縣橫濱市西區", prefecture="神奈川県", city="横浜"),
    s("kanagawa_japanese", "神奈川日本語學院", "Kanagawa Japanese Language Academy", "神奈川日本語学院", "神奈川縣橫濱市神奈川區", prefecture="神奈川県", city="横浜"),
    s("chiba_japanese", "千葉日本語學校", "Chiba Japanese Language School", "千葉日本語学校", "千葉縣千葉市中央區", prefecture="千葉県", city="千葉"),
    s("kashiwa_japanese", "柏日本語學院", "Kashiwa Japanese Language Academy", "柏日本語学院", "千葉縣柏市", prefecture="千葉県", city="柏"),
    # --- Osaka ---
    s("osaka_yMCA", "大阪YMCA學院", "Osaka YMCA Gakuin", "大阪YMCA学院", "大阪府大阪市西區", prefecture="大阪府", city="大阪"),
    s("osaka_japanese_lang", "大阪日本語學院", "Osaka Japanese Language Academy", "大阪日本語学院", "大阪府大阪市中央區", prefecture="大阪府", city="大阪"),
    s("ecc_osaka", "ECC外語學院 大阪校", "ECC Japanese Language Institute Osaka", "ECC外国語学院 大阪校", "大阪府大阪市北區", prefecture="大阪府", city="大阪"),
    s("osaka_intl_lang", "大阪國際語學中心", "Osaka International Language Center", "大阪国際語学センター", "大阪府大阪市北區", prefecture="大阪府", city="大阪"),
    s("human_academy_osaka", "Human Academy 大阪校", "Human Academy Osaka", "ヒューマンアカデミー 大阪校", "大阪府大阪市北區", prefecture="大阪府", city="大阪"),
    s("osaka_school_japanese", "大阪日本語教育センター", "Osaka Japanese Education Center", "大阪日本語教育センター", "大阪府大阪市浪速區", prefecture="大阪府", city="大阪"),
    s("osaka_university", "大阪大學", "Osaka University", "大阪大学", "大阪府吹田市", prefecture="大阪府", city="大阪", type="university"),
    s("kansai_university", "關西大學", "Kansai University", "関西大学", "大阪府吹田市", prefecture="大阪府", city="大阪", type="university"),
    s("ritsumeikan_osaka", "立命館大學 大阪茨木校區", "Ritsumeikan University Osaka Ibaraki", "立命館大学 大阪茨木", "大阪府茨木市", prefecture="大阪府", city="大阪", type="university"),
    # --- Kyoto ---
    s("kyoto_japanese_lang", "京都日本語學校", "Kyoto Japanese Language School", "京都日本語学校", "京都府京都市中京區", prefecture="京都府", city="京都"),
    s("kyoto_culture", "京都文化日本語學校", "Kyoto Culture Japanese Language School", "京都文化日本語学校", "京都府京都市下京區", prefecture="京都府", city="京都"),
    s("kyoto_nihongo_center", "京都日本語センター", "Kyoto Nihongo Center", "京都日本語センター", "京都府京都市中京區", prefecture="京都府", city="京都"),
    s("kyoto_university", "京都大學", "Kyoto University", "京都大学", "京都府京都市左京區", prefecture="京都府", city="京都", type="university"),
    s("doshisha_university", "同志社大學", "Doshisha University", "同志社大学", "京都府京都市上京區", prefecture="京都府", city="京都", type="university"),
    s("ritsumeikan_kyoto", "立命館大學", "Ritsumeikan University", "立命館大学", "京都府京都市中京區", prefecture="京都府", city="京都", type="university"),
    # --- Nagoya / Chubu ---
    s("nagoya_intl_japanese", "名古屋國際日本語學校", "Nagoya International Japanese School", "名古屋国際日本語学校", "愛知縣名古屋市中區", prefecture="愛知県", city="名古屋"),
    s("nagoya_sky", "名古屋SKY日本語學校", "Nagoya SKY Japanese Language School", "名古屋SKY日本語学校", "愛知縣名古屋市中村區", prefecture="愛知県", city="名古屋"),
    s("nagoya_university", "名古屋大學", "Nagoya University", "名古屋大学", "愛知縣名古屋市千種區", prefecture="愛知県", city="名古屋", type="university"),
    s("nagoya_intl_academy", "名古屋國際學院", "Nagoya International Academy", "名古屋国際学院", "愛知縣名古屋市中區", prefecture="愛知県", city="名古屋"),
    # --- Fukuoka / Kyushu ---
    s("fukuoka_japanese", "福岡日本語學校", "Fukuoka Japanese Language School", "福岡日本語学校", "福岡縣福岡市博多區", prefecture="福岡県", city="福岡"),
    s("fukuoka_intl_lang", "福岡國際語學院", "Fukuoka International Language Academy", "福岡国際語学院", "福岡縣福岡市中央區", prefecture="福岡県", city="福岡"),
    s("kyushu_university", "九州大學", "Kyushu University", "九州大学", "福岡縣福岡市東區", prefecture="福岡県", city="福岡", type="university"),
    # --- Hokkaido / Tohoku ---
    s("sapporo_japanese", "札幌日本語學院", "Sapporo Japanese Language Academy", "札幌日本語学院", "北海道札幌市中央區", prefecture="北海道", city="札幌"),
    s("sendai_japanese", "仙台日本語學校", "Sendai Japanese Language School", "仙台日本語学校", "宮城縣仙台市青葉區", prefecture="宮城県", city="仙台"),
    s("tohoku_university", "東北大學", "Tohoku University", "東北大学", "宮城縣仙台市青葉區", prefecture="宮城県", city="仙台", type="university"),
    # --- Other regions ---
    s("hiroshima_intl", "廣島國際學院", "Hiroshima International Academy", "広島国際学院", "廣島縣廣島市中區", prefecture="広島県", city="広島"),
    s("okayama_japanese", "岡山日本語學院", "Okayama Japanese Language Academy", "岡山日本語学院", "岡山縣岡山市北區", prefecture="岡山県", city="岡山"),
    s("kobe_japanese", "神戶日本語學院", "Kobe Japanese Language Academy", "神戸日本語学院", "兵庫縣神戶市中央區", prefecture="兵庫県", city="神戸"),
    s("kobe_university", "神戶大學", "Kobe University", "神戸大学", "兵庫縣神戶市灘區", prefecture="兵庫県", city="神戸", type="university"),
    s("okinawa_japanese", "沖繩日本語教育研究所", "Okinawa Japanese Language Institute", "沖縄日本語教育研究所", "沖繩縣那霸市", prefecture="沖縄県", city="那覇"),
    s("shizuoka_japanese", "靜岡日本語學校", "Shizuoka Japanese Language School", "静岡日本語学校", "靜岡縣靜岡市駿河區", prefecture="静岡県", city="静岡"),
]

base = os.path.dirname(__file__)
out = os.path.join(base, "..", "data", "schools.json")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as f:
    json.dump({"version": "1.0", "schools": SCHOOLS}, f, ensure_ascii=False, indent=2)
print(f"Wrote {len(SCHOOLS)} schools")
