"""Generate data/roadmap.json — study-abroad relocation flow (5-phase model)."""
import json
import os


def t(zh, en, ja):
    return {"zh-TW": zh, "en": en, "ja": ja}


def doc(id_, zh, en, ja, required=True):
    return {"id": id_, "label": t(zh, en, ja), "required": required}


PHASES = [
    {
        "id": "phase_pre_arrival",
        "order": 0,
        "title": t("渡航前準備（母国）", "Pre-departure (home country)", "渡航前準備（母国）"),
    },
    {
        "id": "phase_arrival",
        "order": 1,
        "title": t("入國當日", "Arrival day", "入国当日"),
    },
    {
        "id": "phase_week1",
        "order": 2,
        "title": t("入國後第1週", "First week after arrival", "入国後第1週（行政・生活基盤手続き）"),
    },
    {
        "id": "phase_settlement",
        "order": 3,
        "title": t("生活基盤定著", "Life infrastructure setup", "生活基盤の定着（口座開設完了後）"),
    },
    {
        "id": "phase_id_longterm",
        "order": 4,
        "title": t("中長期身分證明", "Long-term ID documents", "中長期的な身分証明書のアップデート（ID基盤）"),
    },
]

ROUTES = {
    "dorm": {
        "label": t("學校寮・留學生會館", "School dorm / international student hall", "学校の寮・留学生会館"),
        "exclude": [
            "task_housing_rental_managed",
            "task_housing_rental_self",
            "task_gas_activation",
        ],
        "include_only": None,
    },
    "rental": {
        "label": t("民間賃貸（管理公司代辦）", "Private rental (via management company)", "民間の賃貸物件（管理会社経由）"),
        "exclude": [
            "task_housing_dorm",
            "task_housing_rental_self",
        ],
        "include_only": None,
    },
    "housing_tbd": {
        "label": t("個人契約賃貸（自己手配）", "Self-arranged rental", "個人で契約した賃貸物件（自己手配ライフライン）"),
        "exclude": [
            "task_housing_dorm",
            "task_housing_rental_managed",
        ],
        "include_only": None,
    },
}


def task(
    tid,
    phase,
    title_zh,
    title_en,
    title_ja,
    summary_zh,
    summary_en,
    summary_ja,
    depends_on=None,
    routes=None,
    exclude_routes=None,
    school_types=None,
    part_time_only=False,
    skip_if_profile=None,
    duration_min=30,
    priority="normal",
    deadline_days=None,
    documents=None,
    tips=None,
    kind="action",
):
    return {
        "id": tid,
        "phase": phase,
        "kind": kind,
        "title": t(title_zh, title_en, title_ja),
        "summary": t(summary_zh, summary_en, summary_ja),
        "depends_on": depends_on or [],
        "routes": routes,
        "exclude_routes": exclude_routes or [],
        "school_types": school_types,
        "part_time_only": part_time_only,
        "skip_if_profile": skip_if_profile,
        "duration_min": duration_min,
        "priority": priority,
        "deadline_days_after_arrival": deadline_days,
        "documents": documents or [],
        "tips": [t(a, b, c) for a, b, c in (tips or [])],
    }


TASKS = [
    # --- Phase 1: Pre-departure ---
    task(
        "task_study_plan",
        "phase_pre_arrival",
        "制定留學計畫・開始收集資訊",
        "Plan study abroad & gather information",
        "留学計画の策定・情報収集の開始",
        "決定進學路線（語校／大學別科／大學院／專門學校／高中）並開始收集必要資訊",
        "Choose your study path (language school, prep course, university, vocational, high school) and start gathering info",
        "進学ルート（語学学校・大学別科・大学院・専門学校・高校）を決め、必要な情報収集を開始",
        depends_on=[],
        priority="critical",
        duration_min=120,
        tips=[
            ("語校は通常4月・10月入学が多い", "Language schools often start in April/October", "語学学校は4月・10月入学が多い"),
            ("大學需確認EJU或校內考試要求", "Universities may require EJU or entrance exams", "大学はEJUや校内試験の要否を確認"),
        ],
    ),
    task(
        "task_school_admission",
        "phase_pre_arrival",
        "提交出願書類・學校審查",
        "Submit application documents & school review",
        "出願書類の提出・学校側の審査",
        "依募集要項準備並提交出願書類（可透過留學代理或自行申請）",
        "Prepare and submit application documents per school guidelines (via agent or self-application)",
        "募集要項に沿って出願書類を提出（留学支援代理店または個人での直接出願）",
        depends_on=["task_study_plan"],
        priority="critical",
        duration_min=180,
        tips=[
            ("保留所有提交文件的副本", "Keep copies of all submitted documents", "提出書類のコピーを保管"),
            ("翻譯件需確認是否符合入管要求", "Confirm translations meet immigration requirements", "翻訳文が入管要件を満たすか確認"),
        ],
    ),
    task(
        "task_coe_receive",
        "phase_pre_arrival",
        "取得在留資格認定證明書（COE）",
        "Receive Certificate of Eligibility (COE)",
        "在留資格認定証明書（COE）の交付",
        "學校或本人向入管局申請後，收到 COE",
        "Receive COE after application to immigration via school or yourself",
        "学校等が入管に申請し、在留資格認定証明書を受領",
        depends_on=["task_school_admission"],
        priority="critical",
        duration_min=30,
        documents=[doc("coe", "在留資格認定證明書", "Certificate of Eligibility", "在留資格認定証明書")],
    ),
    task(
        "task_visa_apply",
        "phase_pre_arrival",
        "申請簽證（查證）",
        "Apply for visa",
        "ビザ（査証）の申請・発給",
        "持 COE、護照等至本國日本大使館・總領事館申請簽證",
        "Apply at Japanese embassy/consulate with COE and passport",
        "COEとパスポートを持ち、本国の日本大使館・総領事館等でビザ申請",
        depends_on=["task_coe_receive"],
        priority="critical",
        duration_min=60,
        documents=[
            doc("passport", "護照", "Passport", "パスポート"),
            doc("coe", "COE", "COE", "在留資格認定証明書"),
        ],
    ),
    task(
        "task_funds_prep",
        "phase_pre_arrival",
        "準備資金",
        "Prepare funds",
        "資金の準備",
        "設定海外提款（Wise/Revolut等）或準備攜帶現金（超過100萬日圓等值需向海關申報）",
        "Set up international banking/cards (Wise, Revolut, etc.) or prepare cash (declare if over ~1M yen equivalent)",
        "海外送金・複数通貨カードの準備、または多額現金の持参（100万円相当超は税関申告が必要）",
        depends_on=["task_visa_apply"],
        priority="high",
        duration_min=45,
        tips=[
            ("建議同時準備數位支付與少量現金", "Prepare both digital payment and some cash", "デジタル決済と少額現金の両方を用意"),
            ("超過申報額度的現金需向海關申報", "Declare cash above customs threshold", "一定額以上の現金は税関申告"),
        ],
    ),
    task(
        "task_housing_dorm",
        "phase_pre_arrival",
        "學校寮・會館入住手續",
        "School dorm / hall arrangement",
        "学校の寮・留学生会館の手配",
        "向學校申請宿舍；無需入居審查，通常附家具家電，無需自行開通水電",
        "Apply for school dorm; no tenant screening, furnished, utilities often included",
        "学校の寮・留学生会館を申込（審査なし・家具家電付き・ライフライン手続き不要）",
        depends_on=["task_funds_prep"],
        routes=["dorm"],
        priority="critical",
        duration_min=90,
    ),
    task(
        "task_housing_rental_managed",
        "phase_pre_arrival",
        "民間賃貸（管理公司代辦）",
        "Private rental via management company",
        "民間賃貸物件への入居（管理会社経由）",
        "透過管理公司簽約；可委託管理公司事前開通水道・電力",
        "Sign lease via management company; utilities can be pre-arranged through them",
        "管理会社を通じた賃貸契約と水道・電気の事前開始手続き",
        depends_on=["task_funds_prep"],
        routes=["rental"],
        priority="critical",
        duration_min=180,
        tips=[
            ("入居審查通常需1〜2週", "Tenant screening often takes 1-2 weeks", "入居審査は1〜2週間かかることも"),
        ],
    ),
    task(
        "task_housing_rental_self",
        "phase_pre_arrival",
        "個人契約賃貸（自己手配）",
        "Self-arranged private rental",
        "個人で契約した賃貸物件",
        "自行尋找並簽訂租約；到日本後需自行向水電瓦斯公司申請開通",
        "Find and sign lease yourself; contact utility companies after arrival",
        "自分で賃貸契約し、到着後に水道・電気・ガス会社へ契約・開始連絡を実施",
        depends_on=["task_funds_prep"],
        routes=["housing_tbd"],
        priority="critical",
        duration_min=240,
    ),
    task(
        "task_internet_prep",
        "phase_pre_arrival",
        "渡航前網路環境準備",
        "Pre-departure internet setup",
        "渡航前のインターネット環境確保",
        "建議事前申辦日本 eSIM 或實體 SIM，到達後即可使用數據通訊",
        "Consider pre-ordering Japan eSIM or physical SIM for immediate data on arrival",
        "日本国内用eSIMまたは物理SIMの事前契約（到着後すぐにデータ通信が利用可能）",
        depends_on=["task_funds_prep"],
        priority="high",
        duration_min=30,
        skip_if_profile={"sim_at_airport": True},
    ),
    task(
        "task_vjw",
        "phase_pre_arrival",
        "Visit Japan Web 事前登錄",
        "Visit Japan Web pre-registration",
        "Visit Japan Web（オンライン入国手続きサービス）の事前登録",
        "事前登錄以取得入國審查及海關申報用二維碼",
        "Pre-register to get QR codes for immigration and customs",
        "入国審査および税関申告用の二次元コードを取得",
        depends_on=["task_funds_prep"],
        priority="high",
        duration_min=15,
    ),
    task(
        "task_hanko",
        "phase_pre_arrival",
        "準備印章（はんこ）",
        "Prepare personal seal (hanko)",
        "印鑑（はんこ）の事前準備",
        "建議在母國製作印章；銀行開戶及部分租賃契約仍可能需要",
        "Recommended to make seal before departure; needed for bank account and some leases",
        "母国での作成を推奨。銀行口座開設や一部の賃貸契約で依然として有用",
        depends_on=["task_vjw"],
        priority="normal",
        duration_min=20,
        tips=[
            ("可在日本百元店購買簡易印章作備用", "Simple seals available at 100-yen shops in Japan", "日本の100円ショップでも簡易印鑑を購入可"),
        ],
    ),

    # --- Phase 2: Arrival day ---
    task(
        "task_immigration",
        "phase_arrival",
        "入國審查・在留卡領取",
        "Immigration & residence card",
        "入国審査・在留カードの受領",
        "主要機場可當場領取在留卡；地方機場則蓋章後日郵送",
        "Major airports issue residence card on site; regional airports stamp passport for later delivery",
        "主要空港では入国審査時に在留カードを受領。地方空港は後日郵送",
        depends_on=["task_hanko"],
        priority="critical",
        duration_min=60,
        documents=[doc("passport", "護照", "Passport", "パスポート")],
        tips=[
            ("確認姓名拼寫、在留資格與期限", "Verify name spelling, status, and expiry", "氏名・在留資格・期限を確認"),
        ],
    ),
    task(
        "task_work_permit",
        "phase_arrival",
        "資格外活動許可申請",
        "Part-time work permit application",
        "資格外活動許可（アルバイト許可）の申請",
        "若有任何打工可能性，請在入國審查時當場提交申請書",
        "If you might work part-time, submit the application during immigration inspection",
        "少しでもアルバイトを行う可能性がある場合は、入国審査時に必ずその場で申請",
        depends_on=["task_immigration"],
        part_time_only=True,
        priority="high",
        duration_min=15,
    ),
    task(
        "task_transport",
        "phase_arrival",
        "機場交通・交通系IC準備",
        "Airport transport & IC card",
        "空港からの移動・交通系ICの準備",
        "FeliCa 對應手機可發行 Mobile Suica/ICOCA；否則購買實體 IC 卡或現金購票",
        "FeliCa phones can issue Mobile Suica/ICOCA; otherwise buy physical IC card or pay cash",
        "FeliCa対応スマホならモバイルSuica等を即時発行。非対応なら物理ICカードまたは現金",
        depends_on=["task_immigration"],
        priority="high",
        duration_min=20,
    ),
    task(
        "task_move_in",
        "phase_arrival",
        "入住公寓・宿舍",
        "Move in to apartment / dorm",
        "アパート・寮へ移動し入居",
        "前往住所領取鑰匙並完成入住",
        "Travel to your address, receive keys, and move in",
        "住居へ移動し、鍵を受け取って入居",
        depends_on=["task_transport"],
        priority="critical",
        duration_min=60,
    ),
    task(
        "task_gas_activation",
        "phase_arrival",
        "瓦斯開通立會・搬入",
        "Gas activation & move-in setup",
        "ガス開通立ち会い・家具搬入",
        "瓦斯開通需作業員立會點檢；同時安排家具搬入",
        "Gas activation requires staff inspection; arrange furniture delivery",
        "ガス会社の作業員立ち会いによる点検が必須。家具の搬入等も実施",
        depends_on=["task_move_in"],
        exclude_routes=["dorm"],
        priority="high",
        duration_min=90,
        tips=[
            ("事先預約瓦斯公司開通日期", "Book gas activation date in advance", "ガス開通日を事前予約"),
        ],
    ),

    # --- Phase 3: First week ---
    task(
        "task_ward_office",
        "phase_week1",
        "區役所手續（住民登錄・保險・年金）",
        "Ward office (registration, insurance, pension)",
        "市区町村役場での手続き",
        "抵達後14日內完成住民登錄、國民健康保險加入；20歲以上另需國民年金。同時申請保險料減免",
        "Within 14 days: resident registration, national health insurance; pension if 20+. Apply premium reduction",
        "住民登録・国保加入（20歳以上は国年も）。前年所得なしの申告と保険料減免申請を同時に",
        depends_on=["task_move_in"],
        priority="critical",
        duration_min=60,
        deadline_days=14,
        documents=[
            doc("passport", "護照", "Passport", "パスポート"),
            doc("residence_card", "在留卡", "Residence card", "在留カード"),
        ],
        tips=[
            ("同時申請「住民票の写し（マイナンバー記載）」可當場取得個人編號", "Request resident record with My Number on the spot", "マイナンバー記載の住民票の写しを即日発行"),
            ("申告無前年所得可大幅降低保險費", "Declare no prior Japan income for lower premiums", "前年所得なしの申告で保険料が大幅に安くなる"),
        ],
    ),
    task(
        "task_resident_reg_complete",
        "phase_week1",
        "住民登錄完成・在留卡背面記載地址",
        "Resident registration complete",
        "住民登録完了（在留カード裏面に住所記載）",
        "在留卡背面已記載地址；已取得含マイナンバーの住民票副本",
        "Address recorded on residence card; obtained resident record copy with My Number",
        "在留カードの裏面に住所が記載され、マイナンバー記載の住民票の写しを取得",
        depends_on=["task_ward_office"],
        priority="critical",
        duration_min=10,
    ),
    task(
        "task_phone",
        "phase_week1",
        "手機門號本契約",
        "Mobile phone / SIM contract",
        "携帯電話（SIMカード）の本契約",
        "可用海外信用卡線上申辦（ahamo/LINEMO等），或開設銀行帳戶後至店舖契約",
        "Apply online with foreign credit card (ahamo, LINEMO, etc.) or contract in store after bank account",
        "海外クレジットカードでオンライン契約、または銀行口座開設後に店舗・オンラインで契約",
        depends_on=["task_resident_reg_complete"],
        priority="critical",
        duration_min=45,
    ),
    task(
        "task_school_enroll",
        "phase_week1",
        "學校入學・領取學生證",
        "School enrollment & student ID",
        "学校の入学・登校開始（学生証の受領）",
        "完成入學手續並領取學生證（通學定期券・年金免除申請需要）",
        "Complete enrollment and receive student ID (needed for commute pass and pension exemption)",
        "入学手続きを完了し学生証を受領（通学定期・年金猶予に必要）",
        depends_on=["task_resident_reg_complete"],
        priority="critical",
        duration_min=90,
        documents=[
            doc("passport", "護照", "Passport", "パスポート"),
            doc("residence_card", "在留卡", "Residence card", "在留カード"),
        ],
    ),
    task(
        "task_bank",
        "phase_week1",
        "銀行帳戶開設",
        "Bank account opening",
        "銀行口座の開設手続き",
        "推薦ゆうちょ銀行（App申請可、在留半年未滿也可）；都市銀行則審查較嚴",
        "Japan Post Bank recommended (app application, under 6 months OK); megabanks have stricter requirements",
        "ゆうちょ銀行が基本（アプリ申請可・在留半年未満でも可）。メガバンクは要件が厳格",
        depends_on=["task_phone", "task_school_enroll"],
        priority="critical",
        duration_min=60,
        tips=[
            ("需印章與在留卡", "Need seal and residence card", "印鑑と在留カードが必要"),
        ],
    ),
    task(
        "task_commute_pass",
        "phase_week1",
        "通學定期券",
        "Commuter pass",
        "定期券（通学）の購入",
        "若需電車・巴士通學，憑學生證購買通學定期券",
        "If commuting by train/bus, buy student commuter pass with student ID",
        "電車・バス通学の場合は学生証で通学定期券を購入",
        depends_on=["task_school_enroll"],
        priority="normal",
        duration_min=20,
    ),
    task(
        "task_pension_student",
        "phase_week1",
        "國民年金學生納付特例",
        "National pension student exemption",
        "国民年金の学生納付特例制度の申請",
        "20歲以上學生可申請年金保險費猶予・免除（需學生證）",
        "Students 20+ can apply for pension payment deferral/exemption (student ID required)",
        "20歳以上の学生は学生納付特例（支払猶予・免除）を申請可能",
        depends_on=["task_ward_office", "task_school_enroll"],
        priority="high",
        duration_min=30,
    ),

    # --- Phase 4: Settlement ---
    task(
        "task_billing_setup",
        "phase_settlement",
        "公共料金・手機費支付方式變更",
        "Switch utility & phone payment methods",
        "公共料金や携帯電話料金の支払い方法変更",
        "銀行帳戶開設後，將水電瓦斯・手機費改為帳戶自動扣款或日本 debit/信用卡",
        "After bank account: set up auto-debit or Japanese debit/credit card for utilities and phone",
        "銀行口座振替、デビットカード、またはクレジットカード決済への変更",
        depends_on=["task_bank"],
        priority="high",
        duration_min=30,
    ),
    task(
        "task_basics_complete",
        "phase_settlement",
        "基本手續告一段落",
        "Basic procedures complete",
        "基本手続きの一区切り完了",
        "口座・保險・通訊・學校手續等主要事項已完成",
        "Major items (bank, insurance, phone, school) are complete",
        "口座・保険・通信・学校手続きなど主要事項が完了",
        depends_on=["task_billing_setup", "task_commute_pass", "task_pension_student"],
        priority="normal",
        duration_min=5,
        kind="milestone",
    ),

    # --- Phase 5: Long-term ID ---
    task(
        "task_mynumber_notice",
        "phase_id_longterm",
        "領取個人編號通知書",
        "Receive My Number notification",
        "マイナンバー「個人番号通知書」の受け取り",
        "住民登錄後約2〜3週，以簡易掛號郵件寄達家中",
        "Arrives by registered mail ~2-3 weeks after resident registration",
        "住民登録後約2〜3週間で簡易書留で自宅へ到着",
        depends_on=["task_basics_complete"],
        priority="normal",
        duration_min=10,
    ),
    task(
        "task_id_documents",
        "phase_id_longterm",
        "身分證明文件取得",
        "Obtain ID documents",
        "マイナンバー・身分証明書の取得",
        "可申請マイナンバーカード、特定在留カード（2026年6月〜），或暫以通知書保管",
        "Apply for My Number card, Special Residence Card (from Jun 2026), or keep notification for now",
        "マイナンバーカード、特定在留カード（2026年6月14日〜）、または通知書のみ保管",
        depends_on=["task_mynumber_notice"],
        priority="normal",
        duration_min=30,
    ),
    task(
        "task_all_complete",
        "phase_id_longterm",
        "日本定住環境・ID基盤構築完成",
        "Full settlement & ID infrastructure complete",
        "日本での完全な定住環境・身分証明書（ID）基盤の構築が完了",
        "恭喜！主要落地手續與身分證明基盤已全部完成",
        "Congratulations! Settlement and ID infrastructure are fully in place",
        "おめでとうございます！定住環境とID基盤の構築がすべて完了しました",
        depends_on=["task_id_documents"],
        priority="low",
        duration_min=5,
        kind="endpoint",
    ),
]

# Route-specific dependency overrides
for tk in TASKS:
    if tk["id"] in ("task_internet_prep", "task_vjw"):
        tk["route_depends_override"] = {
            "dorm": ["task_housing_dorm"],
            "rental": ["task_housing_rental_managed"],
            "housing_tbd": ["task_housing_rental_self"],
        }
    if tk["id"] == "task_gas_activation":
        tk["route_depends_override"] = {
            "rental": ["task_move_in"],
            "housing_tbd": ["task_move_in"],
        }
    if tk["id"] == "task_ward_office":
        tk["route_depends_override"] = {
            "dorm": ["task_move_in"],
            "rental": ["task_gas_activation"],
            "housing_tbd": ["task_gas_activation"],
        }
    if tk["id"] == "task_work_permit":
        tk["depends_on"] = ["task_immigration"]

roadmap = {
    "version": "3.0",
    "phases": PHASES,
    "routes": ROUTES,
    "tasks": TASKS,
}

out_path = os.path.join(os.path.dirname(__file__), "..", "data", "roadmap.json")
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(roadmap, f, ensure_ascii=False, indent=2)
print(f"Wrote {len(TASKS)} tasks to {out_path}")
