"""Generate data/roadmap_branches.json — user-selectable roadmap branches."""
import json
import os


def t(zh, en, ja):
    return {"zh-TW": zh, "en": en, "ja": ja}


def choice(cid, zh, en, ja, desc_zh="", desc_en="", desc_ja="", unlock=None, hide=None):
    c = {"id": cid, "label": t(zh, en, ja)}
    if desc_zh:
        c["description"] = t(desc_zh, desc_en, desc_ja)
    if unlock:
        c["unlock_tasks"] = unlock
    if hide:
        c["hide_tasks"] = hide
    return c


BRANCH_POINTS = [
    {
        "id": "branch_application_method",
        "task_id": "task_study_plan",
        "prompt": t(
            "出願・申請手続きの進め方は？",
            "How will you handle applications?",
            "出願・申請手続きの進め方",
        ),
        "choices": [
            choice(
                "agent",
                "留學代理店を利用",
                "Via study abroad agent",
                "留学支援代理店を介した手続き",
                "必要書類の確認や翻訳サポート等を依頼。",
                "Agent helps with documents and translations.",
                "必要書類の確認や翻訳サポート等。",
                ["task_application_agent"],
            ),
            choice(
                "self_apply",
                "個人での直接出願",
                "Self-application",
                "個人での直接出願（自己手配）",
                "募集要項に沿って書類を自己手配。",
                "Prepare documents per school guidelines yourself.",
                "募集要項に沿った書類の自己手配。",
                ["task_application_self"],
            ),
        ],
    },
    {
        "id": "branch_funds_prep",
        "task_id": "task_funds_prep",
        "prompt": t(
            "資金の準備形態は？",
            "How will you prepare funds?",
            "資金の準備形態",
        ),
        "choices": [
            choice(
                "digital",
                "デジタル・少額現金",
                "Digital banking & small cash",
                "インターネットバンキング・複数通貨カード",
                "WiseやRevolutなどのカードを準備。",
                "Set up Wise, Revolut, or similar cards.",
                "WiseやRevolutなどの複数通貨対応カードの準備。",
                ["task_funds_digital"],
            ),
            choice(
                "cash",
                "多額の現金を持参",
                "Bring large amount of cash",
                "多額の現金を持参",
                "100万円相当超は税関申告が必要。",
                "Declare to customs if over ~1M yen equivalent.",
                "100万円相当額を超える場合は税関申告が必要。",
                ["task_funds_cash"],
            ),
        ],
    },
    {
        "id": "branch_internet_prep",
        "task_id": "task_internet_prep",
        "prompt": t(
            "渡航前のインターネット環境は？",
            "Pre-departure internet setup?",
            "渡航前のインターネット環境確保",
        ),
        "choices": [
            choice(
                "esim",
                "日本用eSIM・SIMを事前契約",
                "Pre-order Japan eSIM / SIM",
                "日本国内用eSIMまたは物理SIMの事前契約",
                "到着後すぐにデータ通信が利用可能。",
                "Data works immediately on arrival.",
                "日本到着後すぐにデータ通信が利用可能。",
                ["task_internet_esim"],
            ),
            choice(
                "no_prep",
                "事前手配なし",
                "No pre-arrangement",
                "事前の手配なし",
                "到着後は空港Wi-Fiや海外ローミングで一時対応。",
                "Use airport Wi-Fi or roaming temporarily.",
                "到着後に空港の無料Wi-Fiや海外ローミング等で一時的に対応。",
                ["task_internet_later"],
            ),
        ],
    },
    {
        "id": "branch_residence_card",
        "task_id": "task_immigration",
        "prompt": t(
            "入国する空港は？",
            "Which airport are you entering through?",
            "入国する空港による在留カード交付の違い",
        ),
        "choices": [
            choice(
                "major_airport",
                "主要空港（成田・羽田・関空等）",
                "Major airport (Narita, Haneda, KIX, etc.)",
                "主要空港",
                "入国審査時にその場で在留カードを受領。",
                "Receive residence card at immigration counter.",
                "入国審査時にその場で在留カードを受領。",
                ["task_residence_major_airport"],
            ),
            choice(
                "regional_airport",
                "地方空港",
                "Regional airport",
                "その他の地方空港",
                "後日、住民登録後に簡易書留で郵送。",
                "Card mailed after resident registration.",
                "住民登録後に簡易書留で自宅へ郵送。",
                ["task_residence_regional_airport"],
            ),
        ],
    },
    {
        "id": "branch_transport",
        "task_id": "task_transport",
        "prompt": t(
            "空港からの移動方法は？",
            "How will you travel from the airport?",
            "空港からの移動・交通系ICの準備",
        ),
        "choices": [
            choice(
                "ic_felica",
                "FeliCa対応スマホ（モバイルSuica等）",
                "FeliCa phone (Mobile Suica, etc.)",
                "FeliCa対応スマートフォン",
                "iPhone全般、日本国内版Android等。アプリで即時発行。",
                "iPhone or Japan-market Android. Issue via app.",
                "モバイルSuicaやモバイルICOCAなどを即時発行。",
                ["task_transport_mobile_ic"],
            ),
            choice(
                "ic_physical",
                "物理ICカードを購入",
                "Buy physical IC card",
                "FeliCa非対応・物理ICカード",
                "海外版Android等。駅窓口や券売機で購入。",
                "Overseas Android, etc. Buy at station.",
                "駅の窓口や券売機で物理的な交通系ICカードを購入。",
                ["task_transport_physical_ic"],
            ),
            choice(
                "cash_ticket",
                "現金で切符購入",
                "Buy tickets with cash",
                "現金で切符を購入",
                "交通系ICカードは後日必要に応じて発行。",
                "Get IC card later if needed.",
                "交通系ICカードは後日必要に応じて発行。",
                ["task_transport_cash"],
            ),
        ],
    },
    {
        "id": "branch_ward_office",
        "task_id": "task_ward_office",
        "prompt": t(
            "市区町村役場での手続き（年齢）",
            "Ward office procedures (by age)",
            "市区町村役場での手続き",
        ),
        "choices": [
            choice(
                "adult_20",
                "20歳以上",
                "Age 20 or older",
                "20歳以上",
                "住民登録＋国保＋国年加入。保険料減免申請も同時に。",
                "Registration, health insurance, pension. Apply premium reduction.",
                "住民登録＋国保＋国年加入。保険料減免申請を同時に実施。",
                ["task_ward_adult"],
            ),
            choice(
                "minor_under_20",
                "20歳未満",
                "Under age 20",
                "20歳未満",
                "住民登録＋国保加入。保険料減免申請も同時に。",
                "Registration and health insurance. Apply premium reduction.",
                "住民登録＋国保加入。保険料減免申請を同時に実施。",
                ["task_ward_minor"],
            ),
        ],
    },
    {
        "id": "branch_phone_contract",
        "task_id": "task_phone",
        "prompt": t(
            "携帯電話の本契約方法は？",
            "How will you contract a phone plan?",
            "携帯電話（SIMカード）の本契約方法",
        ),
        "choices": [
            choice(
                "online_overseas_card",
                "オンライン・海外クレカ払い",
                "Online with foreign credit card",
                "海外クレジットカード等でオンライン契約",
                "ahamo、LINEMO等。銀行口座がなくても即時取得可能。",
                "ahamo, LINEMO, etc. No Japanese bank needed.",
                "ahamo、LINEMO等。日本の銀行口座がなくても即時に取得可能。",
                ["task_phone_online"],
            ),
            choice(
                "after_bank",
                "口座開設後・店舗契約",
                "In-store after bank account",
                "銀行口座開設後に店舗やオンラインで契約",
                "一時連絡先として学校・寮の番号を利用する手順も。",
                "May use school/dorm number temporarily first.",
                "学校や学生寮の番号を登録し、先に銀行口座を開設。",
                ["task_phone_after_bank"],
            ),
        ],
    },
    {
        "id": "branch_bank_type",
        "task_id": "task_bank",
        "prompt": t(
            "銀行口座の開設先は？",
            "Where will you open a bank account?",
            "銀行口座の開設手続き（主な申請先）",
        ),
        "choices": [
            choice(
                "yucho",
                "ゆうちょ銀行",
                "Japan Post Bank",
                "ゆうちょ銀行",
                "アプリ申請が基本。在留半年未満でも開設可能。",
                "App-based application. OK even under 6 months stay.",
                "ゆうちょ手続きアプリから申請可能。在留期間半年未満でも可。",
                ["task_bank_yucho"],
                ["task_bank_megabank"],
            ),
            choice(
                "megabank",
                "都市銀行・地方銀行",
                "Megabank / regional bank",
                "大手都市銀行・地方銀行",
                "在留半年未満は審査が厳格な場合あり。",
                "Stricter requirements if stay under 6 months.",
                "在留期間半年未満の場合は開設条件や制限が厳格。",
                ["task_bank_megabank"],
                ["task_bank_yucho"],
            ),
        ],
    },
    {
        "id": "branch_commute_pass",
        "task_id": "task_commute_pass",
        "prompt": t(
            "通学定期券は必要ですか？",
            "Do you need a commuter pass?",
            "定期券（通学・通勤）の購入形態",
        ),
        "choices": [
            choice(
                "need_pass",
                "電車・バス通学",
                "Commute by train/bus",
                "通学定期券を購入",
                "学生証や通学証明書が必要。",
                "Student ID or school commute certificate required.",
                "学生証や学校発行の通学証明書が必要。",
                ["task_commute_buy"],
            ),
            choice(
                "no_pass",
                "徒歩・自転車等",
                "Walk or bicycle",
                "定期券不要",
                "交通系ICカード等での都度払い。",
                "Pay per ride with IC card if needed.",
                "交通系ICカード等での都度払い。",
                ["task_commute_skip"],
            ),
        ],
    },
    {
        "id": "branch_pension_exemption",
        "task_id": "task_pension_student",
        "prompt": t(
            "学生納付特例の申請方法は？",
            "How to apply for student pension exemption?",
            "国民年金保険料の学生納付特例制度の申請方法",
        ),
        "choices": [
            choice(
                "ward_direct",
                "市区町村役場で直接申請",
                "Apply at ward office",
                "市区町村役場の国民年金窓口で直接申請",
                "学生証を持参。",
                "Bring student ID.",
                "学生証を持参すること。",
                ["task_pension_ward"],
            ),
            choice(
                "school_proxy",
                "学校・寮の代理申請",
                "Via school or dorm",
                "学校または学生寮を通じた代理申請",
                "所属校の事務所に確認。",
                "Check with your school's office.",
                "所属する学校または学生寮を通じた代理申請。",
                ["task_pension_school"],
            ),
        ],
    },
    {
        "id": "branch_billing_payment",
        "task_id": "task_billing_setup",
        "prompt": t(
            "公共料金・携帯料金の支払い方法は？",
            "How will you pay utilities and phone bills?",
            "公共料金や携帯電話料金の支払い方法変更",
        ),
        "choices": [
            choice(
                "bank_transfer",
                "銀行口座振替",
                "Bank auto-debit",
                "銀行口座振替（自動引き落とし）",
                "最も一般的な支払い方法。",
                "Most common payment method.",
                "最も一般的な支払い方法。",
                ["task_billing_transfer"],
            ),
            choice(
                "debit_card",
                "デビットカード決済",
                "Debit card payment",
                "日本のデビットカード決済",
                "口座開設時に同時発行された場合。",
                "If issued when opening bank account.",
                "銀行口座の開設時に同時に発行された場合。",
                ["task_billing_debit"],
            ),
            choice(
                "credit_card",
                "クレジットカード決済",
                "Credit card payment",
                "日本のクレジットカード決済",
                "後日、国内クレジットカード審査に通過した場合。",
                "After passing Japanese credit card screening.",
                "後日、日本国内のクレジットカード審査に通過した場合。",
                ["task_billing_credit"],
            ),
        ],
    },
    {
        "id": "branch_id_documents",
        "task_id": "task_id_documents",
        "prompt": t(
            "マイナンバー・身分証明書の取得方法は？",
            "How will you obtain ID documents?",
            "マイナンバー・身分証明書の取得方法",
        ),
        "choices": [
            choice(
                "mynumber_card",
                "マイナンバーカードを申請",
                "Apply for My Number card",
                "マイナンバーカードの申請",
                "スマホ等で申請し、後日市区町村で交付。",
                "Apply online, pick up at ward office later.",
                "スマートフォン等で申請し、後日市区町村役場で交付。",
                ["task_mynumber_card_apply"],
            ),
            choice(
                "special_residence_card",
                "特定在留カードへ切り替え",
                "Switch to Special Residence Card",
                "特定在留カードへの切り替え",
                "2026年6月14日より開始。在留期間更新時等に任意申請。",
                "Available from Jun 14, 2026. Optional at renewal.",
                "2026年6月14日より開始。在留期間の更新時などに任意申請可能。",
                ["task_special_residence_card"],
            ),
            choice(
                "notice_only",
                "当面は通知書のみ保管",
                "Keep notification only for now",
                "当面はカード化せず通知書のみ保管",
                "各種手続きでのマイナンバー提示は通知書でも可能。",
                "Notification letter is valid for My Number procedures.",
                "各種手続き等でのマイナンバー提示自体は通知書だけでも可能。",
                ["task_mynumber_notice_only"],
            ),
        ],
    },
]

SUPPLEMENTAL_TASKS = [
    {
        "id": "task_application_agent",
        "phase": "phase_pre_arrival",
        "branch_parent": "task_study_plan",
        "branch_required": {"branch_application_method": "agent"},
        "title": t("留学代理店を介した出願", "Apply via study abroad agent", "留学支援代理店を介した手続き"),
        "summary": t("代理店が書類確認・翻訳をサポート", "Agent supports documents and translation", "必要書類の確認や翻訳サポート等"),
        "depends_on": ["task_study_plan"],
        "duration_min": 60,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_application_self",
        "phase": "phase_pre_arrival",
        "branch_parent": "task_study_plan",
        "branch_required": {"branch_application_method": "self_apply"},
        "title": t("個人での直接出願", "Self-application", "個人での直接出願（自己手配）"),
        "summary": t("募集要項に沿って書類を自己手配", "Prepare documents per guidelines yourself", "募集要項に沿った書類の自己手配"),
        "depends_on": ["task_study_plan"],
        "duration_min": 90,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_funds_digital",
        "phase": "phase_pre_arrival",
        "branch_parent": "task_funds_prep",
        "branch_required": {"branch_funds_prep": "digital"},
        "title": t("デジタル決済・海外カード準備", "Digital payment setup", "インターネットバンキング・複数通貨カードの準備"),
        "summary": t("WiseやRevolut等を設定", "Set up Wise, Revolut, etc.", "WiseやRevolutなどの複数通貨対応カードの準備"),
        "depends_on": ["task_funds_prep"],
        "duration_min": 45,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_funds_cash",
        "phase": "phase_pre_arrival",
        "branch_parent": "task_funds_prep",
        "branch_required": {"branch_funds_prep": "cash"},
        "title": t("多額現金の準備・税関申告確認", "Prepare cash & customs declaration", "多額の現金を持参"),
        "summary": t("100万円相当超は税関申告が必要", "Declare if over ~1M yen equivalent", "100万円相当額を超える場合は税関申告が必要"),
        "depends_on": ["task_funds_prep"],
        "duration_min": 30,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_internet_esim",
        "phase": "phase_pre_arrival",
        "branch_parent": "task_internet_prep",
        "branch_required": {"branch_internet_prep": "esim"},
        "title": t("日本用eSIM・SIM事前契約", "Pre-order Japan eSIM/SIM", "日本国内用eSIMまたは物理SIMの事前契約"),
        "summary": t("到着後すぐにデータ通信が利用可能", "Data ready on arrival", "日本到着後すぐにデータ通信が利用可能"),
        "depends_on": ["task_internet_prep"],
        "duration_min": 30,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_internet_later",
        "phase": "phase_pre_arrival",
        "branch_parent": "task_internet_prep",
        "branch_required": {"branch_internet_prep": "no_prep"},
        "title": t("到着後に通信を手配", "Arrange connectivity after arrival", "事前の手配なし（到着後対応）"),
        "summary": t("空港Wi-Fiやローミングで一時対応", "Use airport Wi-Fi or roaming temporarily", "空港の無料Wi-Fiや海外ローミング等で一時的に対応"),
        "depends_on": ["task_internet_prep"],
        "duration_min": 10,
        "priority": "normal",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_residence_major_airport",
        "phase": "phase_arrival",
        "branch_parent": "task_immigration",
        "branch_required": {"branch_residence_card": "major_airport"},
        "title": t("主要空港で在留カード受領", "Residence card at major airport", "主要空港で在留カードを受領"),
        "summary": t("入国審査時にその場で受領", "Receive at immigration counter", "入国審査時にその場で在留カードを受領"),
        "depends_on": ["task_immigration"],
        "duration_min": 15,
        "priority": "critical",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_residence_regional_airport",
        "phase": "phase_arrival",
        "branch_parent": "task_immigration",
        "branch_required": {"branch_residence_card": "regional_airport"},
        "title": t("地方空港入国（後日郵送）", "Regional airport entry (mailed later)", "地方空港入国・在留カード後日交付"),
        "summary": t("住民登録後に簡易書留で郵送", "Mailed after resident registration", "住民登録後に簡易書留で自宅へ郵送"),
        "depends_on": ["task_immigration"],
        "duration_min": 15,
        "priority": "critical",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_transport_mobile_ic",
        "phase": "phase_arrival",
        "branch_parent": "task_transport",
        "branch_required": {"branch_transport": "ic_felica"},
        "title": t("モバイルSuica/ICOCAを発行", "Issue Mobile Suica/ICOCA", "モバイルSuicaやモバイルICOCAを即時発行"),
        "summary": t("スマホアプリで即時発行", "Issue instantly via phone app", "スマートフォン用アプリ上で即時発行"),
        "depends_on": ["task_transport"],
        "duration_min": 10,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_transport_physical_ic",
        "phase": "phase_arrival",
        "branch_parent": "task_transport",
        "branch_required": {"branch_transport": "ic_physical"},
        "title": t("物理ICカードを購入", "Buy physical IC card", "物理的な交通系ICカードを購入"),
        "summary": t("駅窓口や券売機で購入", "Buy at station counter or ticket machine", "駅の窓口や券売機で購入"),
        "depends_on": ["task_transport"],
        "duration_min": 15,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_transport_cash",
        "phase": "phase_arrival",
        "branch_parent": "task_transport",
        "branch_required": {"branch_transport": "cash_ticket"},
        "title": t("現金で切符を購入して移動", "Buy cash tickets", "現金で切符を購入して移動"),
        "summary": t("ICカードは後日必要に応じて発行", "Get IC card later if needed", "交通系ICカードは後日必要に応じて発行"),
        "depends_on": ["task_transport"],
        "duration_min": 15,
        "priority": "normal",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_ward_adult",
        "phase": "phase_week1",
        "branch_parent": "task_ward_office",
        "branch_required": {"branch_ward_office": "adult_20"},
        "title": t("住民登録・国保・国年（20歳以上）", "Registration, insurance, pension (20+)", "住民登録＋国保＋国年（20歳以上）"),
        "summary": t("保険料減免申請も同時に実施", "Apply premium reduction at same visit", "保険料減免申請を同時に実施"),
        "depends_on": ["task_ward_office"],
        "duration_min": 60,
        "priority": "critical",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_ward_minor",
        "phase": "phase_week1",
        "branch_parent": "task_ward_office",
        "branch_required": {"branch_ward_office": "minor_under_20"},
        "title": t("住民登録・国保（20歳未満）", "Registration & insurance (under 20)", "住民登録＋国保（20歳未満）"),
        "summary": t("保険料減免申請も同時に実施", "Apply premium reduction at same visit", "保険料減免申請を同時に実施"),
        "depends_on": ["task_ward_office"],
        "duration_min": 45,
        "priority": "critical",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_phone_online",
        "phase": "phase_week1",
        "branch_parent": "task_phone",
        "branch_required": {"branch_phone_contract": "online_overseas_card"},
        "title": t("オンラインで携帯契約", "Contract phone online", "オンライン・海外クレカで携帯契約"),
        "summary": t("ahamo、LINEMO等", "ahamo, LINEMO, etc.", "ahamo、LINEMO、外国人向けプラン等"),
        "depends_on": ["task_phone"],
        "duration_min": 40,
        "priority": "critical",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_phone_after_bank",
        "phase": "phase_week1",
        "branch_parent": "task_phone",
        "branch_required": {"branch_phone_contract": "after_bank"},
        "title": t("口座開設後に店舗契約", "Contract in store after bank", "銀行口座開設後に店舗・オンライン契約"),
        "summary": t("学校番号を一時連絡先に利用可能", "May use school number temporarily", "学校や学生寮の番号を一時連絡先に"),
        "depends_on": ["task_phone"],
        "duration_min": 60,
        "priority": "critical",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_bank_yucho",
        "phase": "phase_week1",
        "branch_parent": "task_bank",
        "branch_required": {"branch_bank_type": "yucho"},
        "title": t("ゆうちょ銀行で口座開設", "Japan Post Bank account", "ゆうちょ銀行で口座開設"),
        "summary": t("アプリまたは郵便局窓口", "Via app or post office counter", "ゆうちょ手続きアプリまたは郵便局窓口"),
        "depends_on": ["task_bank"],
        "duration_min": 45,
        "priority": "critical",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_bank_megabank",
        "phase": "phase_week1",
        "branch_parent": "task_bank",
        "branch_required": {"branch_bank_type": "megabank"},
        "title": t("都市銀行で口座開設", "Megabank account", "メガバンク・地方銀行で口座開設"),
        "summary": t("審査が厳格な場合あり", "Screening may be strict", "在留期間や要件により審査が厳格"),
        "depends_on": ["task_bank"],
        "duration_min": 60,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_commute_buy",
        "phase": "phase_week1",
        "branch_parent": "task_commute_pass",
        "branch_required": {"branch_commute_pass": "need_pass"},
        "title": t("通学定期券を購入", "Buy student commuter pass", "通学定期券を購入"),
        "summary": t("学生証が必要", "Student ID required", "学生証や通学証明書が必要"),
        "depends_on": ["task_commute_pass"],
        "duration_min": 20,
        "priority": "normal",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_commute_skip",
        "phase": "phase_week1",
        "branch_parent": "task_commute_pass",
        "branch_required": {"branch_commute_pass": "no_pass"},
        "title": t("定期券不要（徒歩・自転車）", "No commuter pass needed", "定期券不要"),
        "summary": t("都度払いで移動", "Pay per ride as needed", "徒歩・自転車圏内、または都度払い"),
        "depends_on": ["task_commute_pass"],
        "duration_min": 5,
        "priority": "low",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_pension_ward",
        "phase": "phase_week1",
        "branch_parent": "task_pension_student",
        "branch_required": {"branch_pension_exemption": "ward_direct"},
        "title": t("役場で学生納付特例を申請", "Apply at ward office", "市区町村役場で学生納付特例を申請"),
        "summary": t("学生証を持参", "Bring student ID", "学生証を持参"),
        "depends_on": ["task_pension_student"],
        "duration_min": 30,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_pension_school",
        "phase": "phase_week1",
        "branch_parent": "task_pension_student",
        "branch_required": {"branch_pension_exemption": "school_proxy"},
        "title": t("学校・寮経由で代理申請", "Apply via school/dorm", "学校・寮の代理申請"),
        "summary": t("所属校の事務所に確認", "Check with school office", "所属する学校または学生寮を通じた代理申請"),
        "depends_on": ["task_pension_student"],
        "duration_min": 20,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_billing_transfer",
        "phase": "phase_settlement",
        "branch_parent": "task_billing_setup",
        "branch_required": {"branch_billing_payment": "bank_transfer"},
        "title": t("口座振替を設定", "Set up auto-debit", "銀行口座振替を設定"),
        "summary": t("公共料金・携帯料金を自動引き落とし", "Auto-debit for utilities and phone", "公共料金や携帯電話料金の口座振替"),
        "depends_on": ["task_billing_setup"],
        "duration_min": 30,
        "priority": "high",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_billing_debit",
        "phase": "phase_settlement",
        "branch_parent": "task_billing_setup",
        "branch_required": {"branch_billing_payment": "debit_card"},
        "title": t("デビットカード決済に変更", "Switch to debit card", "デビットカード決済に変更"),
        "summary": t("即時決済カードで支払い", "Pay with debit card", "日本のデビットカードで支払い"),
        "depends_on": ["task_billing_setup"],
        "duration_min": 20,
        "priority": "normal",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_billing_credit",
        "phase": "phase_settlement",
        "branch_parent": "task_billing_setup",
        "branch_required": {"branch_billing_payment": "credit_card"},
        "title": t("クレジットカード決済に変更", "Switch to credit card", "クレジットカード決済に変更"),
        "summary": t("国内クレカ審査通過後", "After passing domestic credit screening", "日本国内クレジットカード審査通過後"),
        "depends_on": ["task_billing_setup"],
        "duration_min": 20,
        "priority": "normal",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_mynumber_card_apply",
        "phase": "phase_id_longterm",
        "branch_parent": "task_id_documents",
        "branch_required": {"branch_id_documents": "mynumber_card"},
        "title": t("マイナンバーカードを申請", "Apply for My Number card", "マイナンバーカードの申請"),
        "summary": t("オンライン申請後、役場で交付", "Apply online, pick up at ward office", "スマホ等で申請し、後日市区町村役場で交付"),
        "depends_on": ["task_id_documents"],
        "duration_min": 30,
        "priority": "normal",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_special_residence_card",
        "phase": "phase_id_longterm",
        "branch_parent": "task_id_documents",
        "branch_required": {"branch_id_documents": "special_residence_card"},
        "title": t("特定在留カードへ切り替え", "Switch to Special Residence Card", "特定在留カードへの切り替え"),
        "summary": t("2026年6月14日より開始", "Available from Jun 14, 2026", "2026年6月14日より開始された新制度"),
        "depends_on": ["task_id_documents"],
        "duration_min": 60,
        "priority": "normal",
        "tips": [],
        "documents": [],
    },
    {
        "id": "task_mynumber_notice_only",
        "phase": "phase_id_longterm",
        "branch_parent": "task_id_documents",
        "branch_required": {"branch_id_documents": "notice_only"},
        "title": t("個人番号通知書を保管", "Keep My Number notification", "個人番号通知書のみ保管"),
        "summary": t("当面はカード化せず保管", "Keep notification without applying for card", "当面はカード化せず、通知書を大切に保管"),
        "depends_on": ["task_id_documents"],
        "duration_min": 5,
        "priority": "low",
        "tips": [],
        "documents": [],
    },
]

COMPLETION_ALIASES = {
    "task_study_plan": ["task_application_agent", "task_application_self"],
    "task_funds_prep": ["task_funds_digital", "task_funds_cash"],
    "task_internet_prep": ["task_internet_esim", "task_internet_later"],
    "task_immigration": ["task_residence_major_airport", "task_residence_regional_airport"],
    "task_transport": [
        "task_transport_mobile_ic",
        "task_transport_physical_ic",
        "task_transport_cash",
    ],
    "task_ward_office": ["task_ward_adult", "task_ward_minor"],
    "task_phone": ["task_phone_online", "task_phone_after_bank"],
    "task_bank": ["task_bank_yucho", "task_bank_megabank"],
    "task_commute_pass": ["task_commute_buy", "task_commute_skip"],
    "task_pension_student": ["task_pension_ward", "task_pension_school"],
    "task_billing_setup": ["task_billing_transfer", "task_billing_debit", "task_billing_credit"],
    "task_id_documents": [
        "task_mynumber_card_apply",
        "task_special_residence_card",
        "task_mynumber_notice_only",
    ],
}

out = os.path.join(os.path.dirname(__file__), "..", "data", "roadmap_branches.json")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as f:
    json.dump(
        {
            "version": "2.0",
            "branch_points": BRANCH_POINTS,
            "supplemental_tasks": SUPPLEMENTAL_TASKS,
            "completion_aliases": COMPLETION_ALIASES,
        },
        f,
        ensure_ascii=False,
        indent=2,
    )
print(f"Wrote {len(BRANCH_POINTS)} branch points, {len(SUPPLEMENTAL_TASKS)} supplemental tasks")
